name: CI

on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        matlab_release: [ R2020a, R2020b, R2021a ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab_release }}
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: ./
          test-results-junit: test_report.xml
      - name: Upload test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ./test_report.xml
          check_name: Test results